In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, models
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Age'].fillna(df['Age'].median(),inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)
df['Cabin'].fillna(df['Cabin'].mode()[0],inplace=True)

/tmp/ipython-input-3437686986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)
/tmp/ipython-input-3437686986.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)
/tmp/ipython-input-3437686986.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(df['Cabin'].mode()[0],inplace=True)

In [ ]:
df['Embarked']=df['Embarked'].map({'S':0,'C':1,'Q':2})
df['Sex']=df['Sex'].map({'male':0,'female':1})
df['Cabin']=df['Cabin'].map({'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6})

In [ ]:
X=df[['Age','Pclass','SibSp','Parch','Fare','Embarked','Sex']]
y=df[['Survived']]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)

In [ ]:
X_test.head(3)

      Age  Pclass  SibSp  Parch      Fare  Embarked  Sex
837  28.0       3      0      0    8.0500         0    0
334  28.0       1      1      0  133.6500         0    1
849  28.0       1      1      0   89.1042         1    1

In [ ]:
X_train.sample(5)

      Age  Pclass  SibSp  Parch     Fare  Embarked  Sex
788   1.0       3      1      2  20.5750         0    0
374   3.0       3      3      1  21.0750         0    1
692  28.0       3      0      0  56.4958         0    0
384  28.0       3      0      0   7.8958         0    0
114  17.0       3      0      0  14.4583         1    1

In [ ]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_test

array([[-0.11023411,  0.83022982, -0.47682185, ..., -0.49609507,
        -0.55969464, -0.74015275],
       [-0.11023411, -1.56298327,  0.40728533, ...,  2.16770849,
        -0.55969464,  1.35107247],
       [-0.11023411, -1.56298327,  0.40728533, ...,  1.22295323,
         1.03431569,  1.35107247],
       ...,
       [-0.41361118,  0.83022982, -0.47682185, ..., -0.46534256,
        -0.55969464, -0.74015275],
       [ 0.49652005,  0.83022982,  0.40728533, ..., -0.2977944 ,
        -0.55969464,  1.35107247],
       [-0.03438984, -1.56298327, -0.47682185, ..., -0.0305657 ,
        -0.55969464, -0.74015275]])

In [ ]:
model=models.Sequential([
    layers.Dense(16,activation='relu',input_shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history=model.fit(X_train,y_train,epochs=50,
                  batch_size=32,validation_data=(X_test,y_test))

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 6s 28ms/step - accuracy: 0.6183 - loss: 0.7019 - val_accuracy: 0.6089 - val_loss: 0.6723
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6271 - loss: 0.6592 - val_accuracy: 0.6089 - val_loss: 0.6434
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6127 - loss: 0.6367 - val_accuracy: 0.6145 - val_loss: 0.6206
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6585 - loss: 0.6002 - val_accuracy: 0.6369 - val_loss: 0.5971
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6810 - loss: 0.5839 - val_accuracy: 0.7095 - val_loss: 0.5751
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7389 - loss: 0.5449 - val_accuracy: 0.7430 - val_loss: 0.5532
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7618 - loss: 0.5367 - val_accuracy: 0.7542 - val_loss: 0.5353
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7927 - loss: 0.5036 - val_accuracy: 0.7989 - val_loss: 0.5169
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8037 - loss: 0.4959 - val_accuracy: 0.8156 - val_loss: 0.5028
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8256 - loss: 0.4617 - val_accuracy: 0.8156 - val_loss: 0.4927
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8096 - loss: 0.4565 - val_accuracy: 0.8045 - val_loss: 0.4844
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8243 - loss: 0.4251 - val_accuracy: 0.8045 - val_loss: 0.4803
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8034 - loss: 0.4494 - val_accuracy: 0.8045 - val_loss: 0.4771
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8033 - loss: 0.4372 - val_accuracy: 0.7989 - val_loss: 0.4736
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8200 - loss: 0.4168 - val_accuracy: 0.7933 - val_loss: 0.4695
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8270 - loss: 0.4025 - val_accuracy: 0.7989 - val_loss: 0.4684
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8125 - loss: 0.4082 - val_accuracy: 0.7989 - val_loss: 0.4653
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8047 - loss: 0.4231 - val_accuracy: 0.7989 - val_loss: 0.4623
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8268 - loss: 0.4037 - val_accuracy: 0.7989 - val_loss: 0.4595
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8251 - loss: 0.3985 - val_accuracy: 0.7989 - val_loss: 0.4577
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8368 - loss: 0.3868 - val_accuracy: 0.8045 - val_loss: 0.4557
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8130 - loss: 0.4282 - val_accuracy: 0.7989 - val_loss: 0.4545
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8255 - loss: 0.4047 - val_accuracy: 0.8101 - val_loss: 0.4540
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8300 - loss: 0.3840 - val_accuracy: 0.8045 - val_loss: 0.4530
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8049 - loss: 0.4182 - val_accuracy: 0.8156 - val_loss: 0.4509
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8363 - loss: 0.3991 - val_accuracy: 0.8212 - val_loss: 0.4494
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8120 - loss: 0.4023 - val_accuracy: 0.8156 - val_loss: 0.4479
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8179 - loss: 0.4150 - val_accuracy: 0.8045 - val_loss: 0.4468
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8475 - loss: 0.3791 - val_accuracy: 0.8156 - val_loss: 0.4471
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8377 - loss: 0.3886 - val_accuracy: 0.8101 - val_loss: 0.4467
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8514 - loss: 0.3768 - val_accuracy: 0.8156 - val_loss: 0.4448
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8233 - loss: 0.4029 - val_accuracy: 0.8324 - val_loss: 0.4433
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8353 - loss: 0.3928 - val_accuracy: 0.8324 - val_loss: 0.4428
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8348 - loss: 0.3925 - val_accuracy: 0.8212 - val_loss: 0.4427
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8327 - loss: 0.3752 - val_accuracy: 0.8324 - val_loss: 0.4423
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8408 - loss: 0.3947 - val_accuracy: 0.8324 - val_loss: 0.4425
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8275 - loss: 0.4069 - val_accuracy: 0.8212 - val_loss: 0.4407
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8571 - loss: 0.3672 - val_accuracy: 0.8324 - val_loss: 0.4393
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8136 - loss: 0.4155 - val_accuracy: 0.8324 - val_loss: 0.4390
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8459 - loss: 0.3693 - val_accuracy: 0.8324 - val_loss: 0.4389
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8596 - loss: 0.3669 - val_accuracy: 0.8324 - val_loss: 0.4391
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3640 - val_accuracy: 0.8324 - val_loss: 0.4390
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8437 - loss: 0.3846 - val_accuracy: 0.8324 - val_loss: 0.4382
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3785 - val_accuracy: 0.8380 - val_loss: 0.4374
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8393 - loss: 0.3815 - val_accuracy: 0.8324 - val_loss: 0.4357
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8477 - loss: 0.3778 - val_accuracy: 0.8380 - val_loss: 0.4361
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8467 - loss: 0.3713 - val_accuracy: 0.8380 - val_loss: 0.4363
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8524 - loss: 0.3504 - val_accuracy: 0.8380 - val_loss: 0.4362
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8169 - loss: 0.3946 - val_accuracy: 0.8380 - val_loss: 0.4351
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3644 - val_accuracy: 0.8436 - val_loss: 0.4350

In [ ]:
loss,acc= model.evaluate(X_test,y_test)
loss,acc

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8801 - loss: 0.3954

(0.4350269138813019, 0.8435754179954529)

In [ ]:
X_test[:3],y_test[:3]

(array([[-0.11023411,  0.83022982, -0.47682185, -0.50442349, -0.49609507,
         -0.55969464, -0.74015275],
        [-0.11023411, -1.56298327,  0.40728533, -0.50442349,  2.16770849,
         -0.55969464,  1.35107247],
        [-0.11023411, -1.56298327,  0.40728533, -0.50442349,  1.22295323,
          1.03431569,  1.35107247]]),
      Survived
 837         0
 334         1
 849         1)

In [ ]:
model.predict(X_test[:3])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step

array([[0.09705959],
       [0.991369  ],
       [0.99280995]], dtype=float32)